#Ejercicio1
#print ("Hola mundo!")

#Ejercicio2
#nombre = input ("Ingrese su nombre" )
#print (f"Hola {nombre} !")

#Ejercicio3
#nombre = input ("Ingrese su nombre: ")
#apellido = input ("Ingrese su apellido: ")
#edad = input ("Ingrese su edad: ")
#lugar = input ("Ingrese su lugar de residencia: ")
#print (f"Soy {nombre} {apellido} , tengo {edad} años y vivo en {lugar}.")

#Ejercicio4
#radio = float(input("Ingrese el radio: "))
#area =  3.1416 * (radio * radio)
#perimetro = 2 * 3.1416 * radio
#print (f"El area del círculo es: {area} y el perímetro es: {perimetro} .")

#Ejercicio5
#segundos = int(input("Ingrese la cantidad de segundos"))
#horas = segundos / 3600
#print (f"La cantidad de segundos ingresados son {horas} horas.")

#Ejercicio6
#numero = int(input("Ingrese el número para ver la tabla: "))
#print ( numero * 1)
#print ( numero * 2)
#print ( numero * 3)
#print ( numero * 4)
#print ( numero * 5)
#print ( numero * 6)
#print ( numero * 7)
#print ( numero * 8)
#print ( numero * 9)
#print ( numero * 10)

#Ejercicio7
#num1 = float(input("Ingrese un número ditinto a 0: "))
#num2 = float(input("Ingrese otro número distinto a 0: "))
#sum = num1 + num2
#rest = num1 - num2
#multip = num1 * num2
#divis = num1 / num2
#print (f"El resultado de la suma es: {sum} , la resta es: {rest} , el producto es {multip} y el cociente es: {divis}")

#Ejercicio8
#peso = float(input("Ingrese su peso: "))
#altura = float(input("Ingrese su altura: "))
#indmasacorp = peso / (altura * altura)
#print (f"Su índice de masa corporal es {indmasacorp}")

#Ejercicio9
#cels = float(input("Ingrese la temperatura en grados Celsius: "))
#farenh = (9/5 * cels) + 32
#print (f"La temperatura es de {farenh} grados Fahrenheit")

#Ejercicio10
num1 = int(input("Ingrese un número: "))
num2 = int(input("Ingrese otro número: "))
num3 = int(input("Ingrese el tercer número: "))
prom = (num1 + num2 + num3) / 3
print (f"El promedio de los números ingresados es: {prom}")

#nueva entega


